apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: llama-bot
  name: llama-bot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: DISCORD_TOKEN
                  name: ollama-secret

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: ollama-secret

            - name: OPENAI_MODEL
              value: "llama-3.3-70b-versatile"

            - name: OPENAI_BASE_URL
              value: "https://api.groq.com/openai/v1"

          image: ghcr.io/ozeliurs/ollama-bot:sha-6871e53
          name: llama-bot
          resources: {}
      restartPolicy: Always
status: {}
