apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - sealed-secret.yaml
  - namespace.yaml
images:
  - name: ghcr.io/ozeliurs/ollama-bot
    newTag: sha-4205f88a
