apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - llama-bot-deployment.yaml
  - ollama-secret-sealed.yaml
  - namespace.yaml
images:
  - name: ghcr.io/ozeliurs/ollama-bot
    newTag: 6f3e0b53197aafbc0d40e0ddec46d31345c9c32c