apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - llama-bot-deployment.yaml
  - ollama-secret-sealed.yaml
  - namespace.yaml
images:
  - name: ghcr.io/ozeliurs/ollama-bot
    newTag: f9189ddc6c6927d2b96700b19d41d1f94653d18d