apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: llama-bot
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: llama-bot
  name: llama-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llama-bot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/ollama-bot-default: "true"
        io.kompose.service: llama-bot
    spec:
      containers:
        - env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: DISCORD_TOKEN
                  name: ollama-secret
            - name: OLLAMA_URL
              valueFrom:
                secretKeyRef:
                  key: OLLAMA_URL
                  name: ollama-secret
          image: ghcr.io/ozeliurs/ollama-bot:fefae8d65a83f3b5178c95485dec6f3d9dead6c3
          name: llama-bot
          resources: {}
      restartPolicy: Always
status: {}
