name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ghcr.io
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          tags: ghcr.io/ozeliurs/ollama-bot:latest,ghcr.io/ozeliurs/ollama-bot:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          push: true
      - name: Image digest
        # sed to replace:
        # images:
        #   - name: ghcr.io/ozeliurs/ollama-bot
        #     newTag: fefae8d65a83f3b5178c95485dec6f3d9dead6c3
        # with:
        # images:
        #   - name: ghcr.io/ozeliurs/ollama-bot
        #     newTag: ${{ github.sha }}
        # In manifests/kustomization.yaml
        run: |
          sed -i "s/\(.*name: ghcr.io\/ozeliurs\/ollama-bot\).*$/\1\n    newTag: ${{ github.sha }}/g" manifests/kustomization.yaml